### ISSUE TITLE
bustle crashes when analysing captures: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by schmittlauch** [wjt/bustle#3]
When opening a bustle dbus capture, bustle crashes with the following error: `hGetContents: invalid argument (invalid byte sequence)`

The capturing itself works fine, i.e. it can be done normally with bustle-pcap or also with the gui tool. The capture file itself is completely fine as I can also open it with Wireshark. But once you stop the capture (bustle-gtk) or open the capture file captured with bustle-pcap in the gui, it crashes. Also `bustle --time $CAPTUREFILE` or `bustle --count $CAPTUREFILE` gives the same error.

I'm using bustle-0.5.4 built with ghc-8.0.2 on a gentoo linux with libpcap-1.8.1 and haskell-pcap-0.4.5.2-r1 .

After a quick search I found [this thread](http://debian.2.n7.nabble.com/Bug-846241-Upstream-commit-d81eb812e679d3f2b4f025cc729b415203889377-breaks-bustle-td4001083.html ) that suggests this issue might be related to newer libpcap versions >= 1.8.1

**Comment by wjt** [comment]
Yes, this is caused by a bug/behaviour change in libpcap. It is fixed upstream in libpcap master but not yet in a release. Some details in f62cf6bfa662af4ae39effbbd4891bc619e3b4e9 and in [freedesktop.org bug #100220](https://bugs.freedesktop.org/show_bug.cgi?id=100220). I suggest you ask the Gentoo libpcap packager to backport some patches or package a libpcap snapshot, and/or [install Bustle from Flathub](https://flathub.org/repo/appstream/org.freedesktop.Bustle.flatpakref) which includes the upstream fix.
